<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New Accounts</title>   
    <style>
        .mb-1{
            margin-bottom:1px;
        }
        body{
            font-size:0.8rem;
        }
        .page_break { page-break-before: always; }
    </style>
</head>
<body>
    <div class="container mt-5">
        <table width="100%">
            <tr>
                <td align="center" style="font-size:1rem; font-weight:bold">
                    New Accounts
                </td>
            </tr>
            <tr>
                <td align="center">Date: {{ date('F d, Y',strtotime($from)) }} to {{ date('F d, Y',strtotime($to)) }}</td>
            </tr>
        </table>
       <br>
        @foreach ($areas->sortby('category')->sortBy('name') as $area)
            <table width="100%">
                <tr><td><b>Area: </b>{{$area->name}}</td> <td align="right">Report Generated: {{date('Y-m-d')}}</td>
            </table>
            </b><br><br><br>
            @php $count = 0; $total = 0; $total2=0; @endphp
            <table border='0.5' padding='0' width="100%" cellspacing='0'>
                <thead>
                    <tr class="table-danger">
                        <th><b>Account No.</b></th>
                        <th><b>Account Name</b></th>
                        <th><b>Cycle</b></th>
                        <th><b>Release Date</b></th>
                        <th><b>Area</b></th>
                        <th><b>Posting Date</b></th>
                        <th><b>Posted by</b></th>
                        <th><b>Amount</b></th>
                        <th><b>Released Amount</b></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($loans ?? ''  as $key=>$loan)
                        @if($loan->client->area_id == $area->id)
                            @php $count++; $total+=$loan->principle_amount; $total2+=($loan->principle_amount- ($loan->principle_amount * 0.10)) @endphp
                            <tr>
                                <td align="center">{{$loan->client->client_id}}</td>
                                <td >{{$loan->client->account_name}}</td>
                                <td align="center" >{{$loan->cycle}}</td>
                                <td >{{date('F d, Y', strtotime($loan->rel_date))}}</td>
                                <td> {{$loan->client->area->name}}</td>
                                <td> {{ date('M. d, Y',strtotime($loan->created_at)) }}</td>
                                <td> {{$loan->user->name}}</td>
                                <td  align='right'>P {{number_format($loan->principle_amount,2)}}</td>
                                <td  align='right'>P {{number_format(($loan->principle_amount- ($loan->principle_amount * 0.10)),2)}}</td>
                            </tr>
                        @endif
                    @endforeach
                    @if($count == 0)  
                        <tr><td colspan='9' align='center'>No release recorded for the said date.</td></tr>
                    @else
                        <tr>
                            <th colspan='7' align='right'>Total: </th>
                            <td align='right'>P {{number_format($total,2)}}</td>
                            <td align='right'>P {{number_format($total2,2)}}</td>                            
                        </tr>
                    @endif
                </tbody>
            </table>
            <div class="page_break"></div>
        @endforeach

        <b>Collection Summary Report</b><br><br>
        <table border='0.5' width="50%" padding='0' cellspacing='0'>
            <thead>
                <tr>
                    <th>Area</th>
                    <th>Principal Amount</th>
                    <th>Released Amount</th>
                </tr>
            </thead>
            <tbody>
                @php $summaryTotal = 0; $relTotal = 0; @endphp
                @foreach ($summary as $data) 
                    <tr>
                        <td>{{$data['area']}}</td>
                        <td align="right">P {{number_format($data['amount'],2)}}</td>
                        <td align="right">P {{number_format($data['rel'],2)}}</td>
                        @php $summaryTotal += $data['amount'];  $relTotal+= $data['rel']; @endphp
                    </tr>

                @endforeach
                <tr>
                    <th>Total: </th><td align="right">P {{number_format($summaryTotal,2)}}</td><td align="right">P {{number_format($relTotal,2)}}</td>
                </tr>
            </tbody>
        </table>
        <br><br>

        <p>Report Generated by:</p>

        <br>
        <p><u>{{Auth::user()->first_name}} {{Auth::user()->middle_name}} {{Auth::user()->last_name}}</u></p>
        {{Auth::user()->role->name}} 
    </div>
</body>
</html>